language: c
before_script:
- npm install hexo -g
- npm install
- git config --global user.name "pointertan"
- git config --global user.email "dingfan.pf@gmail.com"
script:
- hexo generate
- hexo deploy
env:
  global:
  - secure: Y1Sqg/1qaHyKkD8mBqxrJalFQJYqQx9l+6wkl6QJyoP1ugTrgiXrwOY/g7UWhbmS35R4OcpU7BddmdCiEMO9vL6OjOwGx1v75HzTnWNJ1ye5McshN5ysl4Ypl0bDEYIwAkbRFuGwWXN1/2ZNF3dS47DEp4bfrjcXI1O0tQRM9WrlQ6Kq8V9g6DCTPB0wvZXUZUEuaNeNtv1KgMhMRyh2Y0+4+8dHHUvC+kBVf/B5EudWqVZDNyQbLSUC5GkWqj9J/R2IQ2kf1tjjkimKkLj1u3k4RE+T6x+D8M/kqXTBD7YYPyTVyeR/v0pidffIZZ92IkJySlLAkFwfkxPSOCtCcd1T81wkLeR0vQIFSXTlpisfKjcK9Cn+XEIuQ6ge2mwJhQsnkFSW6FpOy1oWdJwqQZkKxiM8ChutR9lG21qodB9460Yq3YcCEq/0clGuhNjSNcnklyUUHKiuTSANLnEU+6YEyYqJ4T/gMCjLsy0GrBv/aFP+9afuZkK+1KkjuZHJ63tf39biNJs9v4n35HjUUksrHtZU1zEfrXF94IFr6DqePCjgmwtxb4mn4LX6AeoD+0hy+5Eq5oFjsIAHU2TIHIVBAlMPBOn4Df8GTWxkrztz500ug3z2aGcv+7G6ti2ntqf7X1f8K3uZlNdKFnMUvPKK+eAVQrq5Cpdi0YLWrFU=
